# Site settings
title:          Erg-Reg

# Author
author:
  name:         Raf Verbeelen

# Theme

remote_theme: chesterhow/tale

# Permalinks

permalink:    /:year-:month-:day/:title
paginate:     5

# Gems

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-remote-theme
